### ISSUE TITLE
Gulp Error on Invalid CSS

### ISSUE THREAD

**Issue by Lunokes** [atostudios/osr-sc#1]
Alright mate! Hope you are well. I've started using your Gulp process for our OSRs here and it's mint, but I have noticed that whenever I write the tiniest error in my CSS and press save, Gulp gets an error and the watch tasks just stop completely, so I keep having to go back and type Gulp again and have a new browser open. Is there any way to stop it being so sensitive? I am always making tiny errors I notice as I go which I notice and fix but Gulp just stops...

Cheers!

Luke

**Comment by anthify** [comment]
I'm good, thanks! It's funny as I never bothered to look into this before yet it annoys me too. There is a solution that I will be using from now on.

You just need to add 

```
 .pipe(sass.sync().on('error', sass.logError))
```

To the compile-sass task like the below example

```
gulp.task('compile-sass', ['json-scss'], function() {
    return gulp.src('./src/scss/styles.scss')
    .pipe(sass.sync().on('error', sass.logError))
    .pipe(sass())
    .pipe(gulp.dest('./dist/css'));
});
```

You can find more options with gulp-sass and of course other plugins at npmjs https://www.npmjs.com/package/gulp-sass

I'm glad you're using it, I hope you make some cool upgrades to it.

**Comment by Lunokes** [comment]
What a guy! Cheers mate, I'll get that put in. Yeah I built my first OSR with it yesterday and it was incredibly easy, I'll be building everything with it now, so thanks for all your work. See you tomorrow night if you're at Frontend NE.
